name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  # ---Backend (Python) + Postgres ---
  backend:
    name: Backend (Python)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd="pg_isready -U testuser -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt"; fi
          # Ensure test & quality tools are present even if not in requirements.txt
          python -m pip install pytest flake8 black bandit psycopg2-binary
                    
      - name: Set test env
        run: |
          echo "DATABASE_URL=postgresql://testuser:testpass@127.0.0.1:5432/testdb" >> $GITHUB_ENV
          
      # OPTIONAL: run minimal migration/bootstrap script if you have one
      - name: DB bootstrap (optional)
        run: |
          if [ -f scripts/bootstrap.sql ]; then psql "$DATABASE_URL" -f scripts/bootstrap.sql; fi
          if [ -f scripts/migrate.py ]; then python scripts/migrate.py; fi

      - name: Lint (flake8)
        run: flake8 || true

      - name: Format check (black)
        run: black --check . || true
  
      - name: Security scan (bandit)
        run: bandit -r . || true

      - name: Run tests
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: |
          if [ -d tests ]; then python -m pytest -q; else echo "No tests configured"; fi

      - name: Package artifact
        run: |
          mkdir -p ../artifacts
          # Replace with your real packaging command when ready
          echo "placeholder artifact" > ../artifacts/backend.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: artifacts/ 
  # ---------- FRONTEND: Static HTML/CSS/JS checks ----------
  frontend:
    name: Frontend (Static checks)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure frontend folder exists
        run: |
          if [ -d frontend ]; then echo "Found /frontend"; else echo "No frontend folder" && exit 0; fi

      # Broken link check (external links allowed; adjust as needed)1
      - name: Link check (Lychee)
        uses: lycheeverse/lychee-action@v1
        with:
          # scan your static site files
          args: --verbose --no-progress "frontend/**/*.html"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}          
          
    